///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VSTS_Integration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VSTS_IntegrationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("195dbadf-4608-44cc-b5ba-bad36d029e51")]
    public partial class VSTS_IntegrationRepository : RepoGenBaseFolder
    {
        static VSTS_IntegrationRepository instance = new VSTS_IntegrationRepository();
        VSTS_IntegrationRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;

        /// <summary>
        /// Gets the singleton class instance representing the VSTS_IntegrationRepository element repository.
        /// </summary>
        [RepositoryFolder("195dbadf-4608-44cc-b5ba-bad36d029e51")]
        public static VSTS_IntegrationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VSTS_IntegrationRepository() 
            : base("VSTS_IntegrationRepository", "/", null, 0, false, "195dbadf-4608-44cc-b5ba-bad36d029e51", ".\\RepositoryImages\\VSTS_IntegrationRepository195dbadf.rximgres")
        {
            _ranorexvipdatabasetestwebapplicatio = new VSTS_IntegrationRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("195dbadf-4608-44cc-b5ba-bad36d029e51")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("69a0d84c-8fd2-4fbc-b0f4-2469990f1b7c")]
        public virtual VSTS_IntegrationRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class VSTS_IntegrationRepositoryFolders
    {
        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("69a0d84c-8fd2-4fbc-b0f4-2469990f1b7c")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _clearInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "69a0d84c-8fd2-4fbc-b0f4-2469990f1b7c", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "e1598022-f57a-4feb-b721-4b29326755fe");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "5e2c5c99-7d44-4915-957f-91fc234721a9");
                _musicInfo = new RepoItemInfo(this, "Music", ".//select[#'Category']/option[@value='Music']", 30000, null, "5c8cf006-6ffb-46b2-a7fd-d6bbd8bcbff8");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "1a5ceeaf-4b7e-4a2c-a677-963a4154607c");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "03110f5f-2856-45c8-a95e-4c23a379747a");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "5fa51e16-b81c-4448-9f7c-3f4948ad3de9");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", 30000, null, "d446cd55-2b5d-4034-96e6-ac55de2efdd6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("69a0d84c-8fd2-4fbc-b0f4-2469990f1b7c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("69a0d84c-8fd2-4fbc-b0f4-2469990f1b7c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("e1598022-f57a-4feb-b721-4b29326755fe")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("e1598022-f57a-4feb-b721-4b29326755fe")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("5e2c5c99-7d44-4915-957f-91fc234721a9")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("5e2c5c99-7d44-4915-957f-91fc234721a9")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("5c8cf006-6ffb-46b2-a7fd-d6bbd8bcbff8")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("5c8cf006-6ffb-46b2-a7fd-d6bbd8bcbff8")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("1a5ceeaf-4b7e-4a2c-a677-963a4154607c")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("1a5ceeaf-4b7e-4a2c-a677-963a4154607c")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("03110f5f-2856-45c8-a95e-4c23a379747a")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("03110f5f-2856-45c8-a95e-4c23a379747a")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("5fa51e16-b81c-4448-9f7c-3f4948ad3de9")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("5fa51e16-b81c-4448-9f7c-3f4948ad3de9")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("d446cd55-2b5d-4034-96e6-ac55de2efdd6")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("d446cd55-2b5d-4034-96e6-ac55de2efdd6")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}